version: '3.8'

services:
  bot:
    build: .
    container_name: bitbuddy-bot
    restart: unless-stopped
    volumes:
      - ./data:/app/data  # Persistent storage for database
      - ./.env:/app/.env  # Mount environment file
    environment:
      - TZ=UTC
    ports:
      - "8000:8000"  # Health check port
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  bitbuddy_data:
    name: bitbuddy_data 